### ISSUE TITLE
 TypeError: Cannot read property 'setMirror' of undefined

### ISSUE THREAD

**Issue by dotnetdreamer** [triniwiz/nativescript-webrtc#3]
### Which platform(s) does your issue occur on?
- Android
- device. What type of device?: S9+

I tried to add this in Angular but getting following error. Here is my code:
```
import { Component, AfterViewInit, ViewChild, ElementRef } from "@angular/core";
import * as app from "application";
import { RadSideDrawer } from "nativescript-ui-sidedrawer";
import { WebRTC, WebRTCView } from 'nativescript-webrtc-plugin';
import { registerElement } from 'nativescript-angular';

registerElement("webrtc", () => WebRTCView);

@Component({
    selector: "Home",
    moduleId: module.id,
    templateUrl: "./home.component.html"
})
export class HomeComponent implements AfterViewInit {
    @ViewChild('remoteVideoView') remoteView: ElementRef;
    @ViewChild('localVideoView') localView: ElementRef;
    
    remoteVideoView: WebRTCView;
    localVideoView: WebRTCView;

    localStream: any;
    remoteStream: any;
    
    constructor() {
        // Use the component constructor to inject providers.
    }

    async ngAfterViewInit() {
        this.remoteVideoView = this.remoteView.nativeElement;
        this.localVideoView = this.localView.nativeElement;

        // Init your component properties here.
        const webrtc = new WebRTC({
            enableAudio: true, // default true
            enableVideo: false, // default true
        });
        if (WebRTC.hasPermissions()) {
            this.localStream = await webrtc.getUserMedia(4);
            this.stream();

            // this.notify({
            //     eventName: 'localStream',
            //     object: fromObject({})
            // });
        } else {
            try {
                await WebRTC.requestPermissions();
                if (WebRTC.hasPermissions()) {
                    this.localStream = await webrtc.getUserMedia(4);
                    this.stream();
                    // this.notify({
                    //     eventName: 'localStream',
                    //     object: fromObject({})
                    // });
                }
            } catch (e) {  
            }
        }
    }

    onDrawerButtonTap(): void {
        const sideDrawer = <RadSideDrawer>app.getRootView();
        sideDrawer.showDrawer();
    }

    private stream() {
        console.dir(this.remoteVideoView);
       //getting error somehow here
        this.localVideoView.mirror = true;

        this.localVideoView.stream = this.localStream;
    };
}
```
View:
```
<ActionBar class="action-bar">
    <!-- 
    Use the NavigationButton as a side-drawer button in Android
    because ActionItems are shown on the right side of the ActionBar
    -->
    <NavigationButton ios:visibility="collapsed" icon="res://menu" (tap)="onDrawerButtonTap()"></NavigationButton>
    <!-- 
    Use the ActionItem for IOS with position set to left. Using the
    NavigationButton as a side-drawer button in iOS is not possible,
    because its function is to always navigate back in the application.
    -->
    <ActionItem icon="res://navigation/menu" android:visibility="collapsed" (tap)="onDrawerButtonTap()"
        ios.position="left">
    </ActionItem>
    <Label class="action-bar-title" text="Home"></Label>
</ActionBar>

<GridLayout rows="*,*" class="page page-content">
    <webrtc row="0" #remoteVideoView height="50%"></webrtc>
    <webrtc row="1" #localVideoView height="50%"></webrtc>
</GridLayout>
```
output:
```
JS: _hi...
JS: ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'setMirror' of undefined
JS: TypeError: Cannot read property 'setMirror' of undefined
JS:     at WebRTCView.set [as mirror] (file:///data/data/org.nativescript.mydrawerng/files/app/tns_modules/nativescript-webrtc-plugin/webrtc.js:431:29)
JS:     at HomeComponent.stream (file:///data/data/org.nativescript.mydrawerng/files/app/home/home.component.js:58:36)
JS:     at HomeComponent.<anonymous> (file:///data/data/org.nativescript.mydrawerng/files/app/home/home.component.js:29:30)
JS:     at step (file:///data/data/org.nativescript.mydrawerng/files/app/tns_modules/nativescript-webrtc-plugin/async-await.js:31:23)
JS:     at Object.next (file:///data/data/org.nativescript.mydrawerng/files/app/tns_modules/nativescript-webrtc-plugin/async-await.js:12:53)
JS:     at fulfilled (file:///data/data/org.nativescript.mydrawerng/files/app/tns_modules/nativescript-webrtc-plugin/async-await.js:3:58)
JS:     at ZoneDelegate.invoke (file:///data/data/org.nativescript.mydrawerng/files/app/tns_mo...
```

**Comment by dotnetdreamer** [comment]
I think it was issue related to LiveSync. When i restart application then it worked fine. I will investigate this.

**Comment by dotnetdreamer** [comment]
@triniwiz  i think there is some internal error. i am only using       `  this.localVideoView.mirror = true;`
 if i comment this then i am getting error in `this.localVideoView.stream`

**Comment by dotnetdreamer** [comment]
@triniwiz  you can take alook at [this ](https://github.com/dotnetdreamer/nativescript-webrtc-issue)sample repository. I have added cod [here](https://github.com/dotnetdreamer/nativescript-webrtc-issue/tree/master/app/home)

**Comment by triniwiz** [comment]
Have you tried nuking (deleting) the platforms ?

**Comment by triniwiz** [comment]
if that fails you can try updating  your app.gradle to [this](https://github.com/triniwiz/nativescript-webrtc/blob/master/demo/app/App_Resources/Android/app.gradle)

**Comment by dotnetdreamer** [comment]
I removed the platform and re-add it. Still was getting same error and application crash. When i add `https://github.com/triniwiz/nativescript-webrtc/blob/master/demo/app/App_Resources/Android/app.gradle` still getting same.

**Comment by triniwiz** [comment]
Can you try the following

```xml
<webrtc row="0" (loaded)="localLoaded($event)"  #localVideoView height="50%"></webrtc>
```

```ts
declare var co: any;

// check if the project is loading the lib
console.log(co.fitcom.fancywebrtc.FancyWebRTCView)

localLoaded(event){
// should log be an instance of co.fitcom.fancywebrtc.FancyWebRTCView
console.log(event.object.nativeView);
}
```

**Comment by dotnetdreamer** [comment]
yes. the first console the function `function () { [native code] }` and second one object `co.fitcom.fancywebrtc.FancyWebRTCView{4ec947b V.E...... ......I. 0,0-0,0}`

**Comment by triniwiz** [comment]
Good good now on the `localLoaded` event call `event.object.mirror = true` if it complains about .mirror is not existing try `(event.object as any).mirror = true` if that doesn't crash then you can set the `this.localVideoView = event.object`

**Comment by triniwiz** [comment]
From your code you are calling `this.stream();` which tries to set the mirror and stream on an `undefined`  `this.localVideoView`

**Comment by dotnetdreamer** [comment]
i have commented all this code. I guess on WebRTC.init() there is permission request and after permissions its crashing. No code is running in component.

**Comment by triniwiz** [comment]
Where are you calling the init ?

**Comment by triniwiz** [comment]
@dotnetdreamer this should be fixed in the v1 feel to repo

**Comment by dotnetdreamer** [comment]
@triniwiz  tried the demo app from repository. Its working now thanks (y)
