### ISSUE TITLE
Is there any plain Javascript demo available?

### ISSUE THREAD

**Issue by thecicada** [triniwiz/nativescript-webrtc#30]
Hi @triniwiz triniwiz
Is there any plain JavaScript demo available?

**Comment by triniwiz** [comment]
No but it should not be similar to the typescript demo

**Comment by thecicada** [comment]
Thanks for your quick response.

Kinda having hard time adding it to my project, I didn't have issue with the installation but I can't get it to work. video is not streaming on the screen, can't even see my local camera streaming on the screen. It would be great if you'd help with how to implement those files as plain JS: call-page.xml, call-page.js, call-view-model.js

Thank you.

**Comment by adekunle11** [comment]
Hello, i would appreciate this also. thanks

**Comment by triniwiz** [comment]
I can try fitting in on the next update

**Comment by adekunle11** [comment]
@triniwiz thank you very much!!
i wish you could see how happy i am hearing that
Please when should we be expecting the next update?

**Comment by adekunle11** [comment]
@triniwiz i just noticed another error in nativesrcript core JS.
The app crashes on launch, the error is:
```
An uncaught Exception occurred on "pool-2-thread-1" thread.
co/fitcom/fancywebrtc/FancyWebRTCEglUtils

StackTrace:
java.lang.VerifyError: co/fitcom/fancywebrtc/FancyWebRTCEglUtils
	at co.fitcom.fancywebrtc.FancyWebRTC.lambda$init$0(FancyWebRTC.java:93)
	at co.fitcom.fancywebrtc.-$$Lambda$FancyWebRTC$jFoisGouehK4C4J-BYA5BfOZep4.run(lambda)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
```
this is my app.js
```
const application = require("tns-core-modules/application");
var Vibrate = require("nativescript-vibrate").Vibrate;
const appSettings = require("tns-core-modules/application-settings");
require("./async-await.js");
var vibrator = new Vibrate();
import { ImageCacheIt } from 'nativescript-image-cache-it';
import { WebRTC } from 'nativescript-webrtc-plugin';
ImageCacheIt.enableAutoMM();

if (application.android) {
    application.android.on(application.AndroidApplication.activityBackPressedEvent, backEvent);
}
function backEvent(args) {
    //args.cancel = true;
    if (appSettings.getBoolean("vibrationSwitch") === true) {
        vibrator.vibrate(25);
    } 
}
WebRTC.init();
application.run({ moduleName: "app-root" });
```

**Comment by triniwiz** [comment]
I'm currently trying to update all the [plugins](https://github.com/triniwiz/plugins/issues/1) to support {N} v7 , I'm trying to complete the list before publishing about your issue please share the error

**Comment by adekunle11** [comment]
> I'm currently trying to update all the [plugins](https://github.com/triniwiz/plugins/issues/1) to support {N} v7 , I'm trying to complete the list before publishing about your issue please share the error

Alright, i have edited the comment

**Comment by triniwiz** [comment]
Ah thanks did you add [this](https://github.com/triniwiz/nativescript-webrtc/blob/master/demo/app/App_Resources/Android/app.gradle#L11-L14) ?

**Comment by adekunle11** [comment]
> Ah thanks did you add [this](https://github.com/triniwiz/nativescript-webrtc/blob/master/demo/app/App_Resources/Android/app.gradle#L11-L14) ?

I added it as :

```
  compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
  }
```
That's how it is in the documentation, but i'm changing it to this:
```
compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }
```

Will let you know the outcome shortly

**Comment by adekunle11** [comment]
@triniwiz unfortunately, its the same issue

**Comment by triniwiz** [comment]
Can you try running the demo ?

**Comment by adekunle11** [comment]
Its giving me so many errors, not the app
the build, i'm used to using Nativescript core JAVASCRIPT, i had to create a typescript project to test this so i'm not used to typescript development
![Capture](https://user-images.githubusercontent.com/45455861/95666961-2f62da80-0b57-11eb-82e6-ad383987cdf9.PNG)

**Comment by adekunle11** [comment]
> Can you try running the demo ?

Hello, any update?

**Comment by triniwiz** [comment]
I’ll take a look and try setting up a js project 


Sent from Yahoo Mail for iPhone


On Sunday, October 11, 2020, 2:20 PM, adekunle11 <notifications@github.com> wrote:





Can you try running the demo ?


Hello, any update?

**Comment by adekunle11** [comment]
> I’ll take a look and try setting up a js project  Sent from Yahoo Mail for iPhone On Sunday, October 11, 2020, 2:20 PM, adekunle11 <notifications@github.com> wrote: Can you try running the demo ? Hello, any update? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks a lot!

**Comment by adekunle11** [comment]
hello @triniwiz  just checking in to see if there's any progress

**Comment by triniwiz** [comment]
@adekunle11 not yet but soon I'm still on stripe atm finalizing the new api

**Comment by adekunle11** [comment]
Okay thanks @triniwiz

**Comment by adekunle11** [comment]
Hello @triniwiz 
Hope you're good
Any update?
tryna see if I can submit the app before next month

**Comment by adekunle11** [comment]
Hello @triniwiz 
I set up a Nativescript core typescript project and its still giving the pool thread error
This is my app.gradle 
```
android {
  defaultConfig {
    minSdkVersion 17
    generatedDensities = []
  }
  aaptOptions {
    additionalParameters "--no-version-vectors"
  }
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }
}
```
This is yours
```
android {
  compileSdkVersion 28
  defaultConfig {
    minSdkVersion 17
    generatedDensities = []
  }
  aaptOptions {
    additionalParameters "--no-version-vectors"
  }

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }
}

```
The only difference is `compileSdkVersion 28`. how important is that, could it be the issue?

**Comment by triniwiz** [comment]
Should not be a problem , I'll need to do some tests

**Comment by adekunle11** [comment]
Don't think you need to anymore, i was going through the closed issues and i saw on that said i should set my minSdkVersion to 24 now the app launches but that means it won't work on my android 4.3 anymore so i'm testing with google's apkonline. so far so good. i didn't want to say anything until i actually tested that its working. so i'm integrating now. How about the plain Javascript demo? @triniwiz

**Comment by adekunle11** [comment]
Hello @triniwiz 
I'm already converting the code to javascript so i can share the code with you later. But rn, i'm getting an error in my call-page.ts.
it says `cannot read property 'from' of undefined`. can you help me check it out please?
i already uploaded the code in the home folder of [this](https://play.nativescript.org/?template=play-js&id=MhaZhC)
Thanks

**Comment by adekunle11** [comment]
Hello @triniwiz , will converting the demo in STARDARD folder from Typescript to javascript work or i'll have to add typescript to my project to use this plugin?

I already tried converting to javascript [here](https://play.nativescript.org/?template=play-js&id=b56Iac&v=5)
but it doesn't work so i want to be sure if i'm doing it the wrong way or just converting the demo to javascript won't work with the plugin

**Comment by adekunle11** [comment]
Hello @triniwiz , I converted my project to typescript now I can use the plugin, thanks.
I'm trying to use the plugin to create a private call system (maximum of 2 people) but i don't think any of the examples in demo-server were created to work with the files in the standard folder.
This is my server code below (I already tried tweaking it, but it doesnt work)
const express = require('express')
const app = express()
const server = require('http').createServer(app)
const io = require('socket.io')(server)

const nspChat = io.of('/chat')
const nspDefault = io.nsps['/']

let messageList = []
let userList = []
let userMap = new Map();
function getOtherUser(id) {
	const keys = Array.from(userMap.keys());
	const filtered = keys.filter((value) => {
		if (value.indexOf(id) === -1) {
			return value;
		}
	});
	return userMap.get(filtered[0]);
}
io.on('connection', function (socket) {
    userMap.set(socket.id, "");
	console.log('User Connected: -> ' + socket.id);
    socket.emit('connected', 'Welcome');
    let addedUser = false;

    socket.on('add user', function (data) {
        if (addedUser) return;
        addedUser = true;
        socket.username = data.username;
        console.log('Username: ', data.username);
        userList.push({
            username: data.username
        });

        socket.emit('login', {
            userList: userList
        });

        socket.broadcast.emit('user joined', {
            username: data.username
        });

        socket.join(data.username);
    });

    socket.on('call', function (data) {
        const otherId = getOtherUser(socket.id);
        console.log('call from', data.from);
        console.log('call to', otherId);
        io.sockets.in(otherId).emit('call:incoming', data, {
            to:otherId
        });
    });

    socket.on('iceCandidate', function (data) {
        const otherId = getOtherUser(socket.id);
        console.log('iceCandid from: ' + data.from + ' to: ' + otherId + ' sdp: ' + data.sdp);
        io.sockets.in(data.to).emit('call:iceCandidate',  Object.assign({}, data, {
            to: otherId
        }));
    });

    socket.on('answer', function (data) {
        console.log('answer from', data.from);
        //console.log('answer to', data.to);
        const otherId = getOtherUser(socket.id);
        console.log("answer to: " + otherId);
        io.in(otherId).emit('call:answer', {
			from: data.from,
			sdp: data.sdp,
			to: otherId
		});
    });

    socket.on('answered', function (data) {
        console.log('answer from', data.from);
        console.log('answer to', data.to);
        io.sockets.in(data.to).emit('call:answered', data);
    })

    socket.on('new message', function (data, cb) {
        cb(true);
        console.log(data);
        messageList.push(data);
        socket.broadcast.emit('new message', data);
    })

    socket.on('getUsers', function () {
        socket.emit('getUsers', userList);
    })
    socket.on('user count', function () {
        socket.emit('user count', userList.length)
    })
    socket.on('getMessages', function () {
        socket.emit('getMessages', messageList)
    })

    socket.on('disconnect', function () {
        console.log('User Disconnected');
        if (addedUser) {
            for (let i = 0; i < userList.length; i++) {
                if (socket.username === userList[i].username) {
                    userList.splice(i, 1);
                }
            }
            socket.broadcast.emit('user left', {
                username: socket.username
            });

            socket.emit('getUsers', userList);
        }
    })
})

nspDefault.on('connect', (socket) => {
    console.log('Joined Namespace: /')
    socket.on('disconnect', () => {
        console.log('Left Namespace: /')
    })
})

nspChat.on('connect', (socket) => {
    console.log('Joined Namespace: /chat')

    socket.on('disconnect', () => {
        console.log('Left Namespace: /chat')
    })
})

server.listen(3000, function() {
    console.log("Listening on 3000");
});

This is my server console.log 
```
Listening on 3000
Joined Namespace: /
User Connected: -> Md2E__SzVn6dNZJtAAAA
Username:  Adekunle@gmail.com
Joined Namespace: /
User Connected: -> 7jOw68WGbVZSQmP1AAAB
Username:  Kulkunzy@gmail.com
Left Namespace: /
User Disconnected
Joined Namespace: /
User Connected: -> Tw7-BqI8LE5THxQuAAAC
Left Namespace: /
User Disconnected
Joined Namespace: /
User Connected: -> -_wc61Y9KdIEwbXTAAAD
Left Namespace: /
User Disconnected
call from 2b520e7d-81b0-90ca-9bbc-d300e1bafc5f
call to
iceCandid from: 2b520e7d-81b0-90ca-9bbc-d300e1bafc5f to:  sdp: candidate:3193961629 1 udp 2122260223 192.168.8.103 36152 typ host generation 0 ufrag Rogl network-id 3 network-cost 10
iceCandid from: 2b520e7d-81b0-90ca-9bbc-d300e1bafc5f to:  sdp: candidate:559267639 1 udp 2122202367 ::1 45352 typ host generation 0 ufrag Rogl network-id 2
iceCandid from: 2b520e7d-81b0-90ca-9bbc-d300e1bafc5f to:  sdp: candidate:1510613869 1 udp 2122129151 127.0.0.1 52708 typ host generation 0 ufrag Rogl network-id 1
iceCandid from: 2b520e7d-81b0-90ca-9bbc-d300e1bafc5f to:  sdp: candidate:3193961629 1 udp 2122260223 192.168.8.103 51352 typ host generation 0 ufrag Rogl network-id 3 network-cost 10
iceCandid from: 2b520e7d-81b0-90ca-9bbc-d300e1bafc5f to:  sdp: candidate:559267639 1 udp 2122202367 ::1 59969 typ host generation 0 ufrag Rogl network-id 2
Joined Namespace: /
User Connected: -> 8pjTwgA7gsD_aiDSAAAE
iceCandid from: 2b520e7d-81b0-90ca-9bbc-d300e1bafc5f to:  sdp: candidate:1510613869 1 udp 2122129151 127.0.0.1 45903 typ host generation 0 ufrag Rogl network-id 1
iceCandid from: 2b520e7d-81b0-90ca-9bbc-d300e1bafc5f to:  sdp: candidate:1876313031 1 tcp 1518222591 ::1 41769 typ host tcptype passive generation 0 ufrag Rogl network-id 2
iceCandid from: 2b520e7d-81b0-90ca-9bbc-d300e1bafc5f to:  sdp: candidate:344579997 1 tcp 1518149375 127.0.0.1 34804 typ host tcptype passive generation 0 ufrag Rogl network-id 1
iceCandid from: 2b520e7d-81b0-90ca-9bbc-d300e1bafc5f to:  sdp: candidate:1876313031 1 tcp 1518222591 ::1 38122 typ host tcptype passive generation 0 ufrag Rogl network-id 2
iceCandid from: 2b520e7d-81b0-90ca-9bbc-d300e1bafc5f to:  sdp: candidate:344579997 1 tcp 1518149375 127.0.0.1 43272 typ host tcptype passive generation 0 ufrag Rogl network-id 1
```

You can see the 'to' is empty, so the main problem is setting the value to the ID the other device generated in `standard-vm.ts`

Thanks in Advance
