### ISSUE TITLE
Webrtc run on nativescript vue error 

### ISSUE THREAD

**Issue by soufianelb** [triniwiz/nativescript-webrtc#49]
Can anyone help me. i run the project in a vue when it starts, i get the following error:
No static method create() lorg/webrtc/EglBase in class Lorg/webrtc...

**Comment by AGregorc** [comment]
I get the same error: 

An uncaught Exception occurred on "pool-1-thread-1" thread.
No static method create()Lorg/webrtc/EglBase; in class Lorg/webrtc/EglBase; or its super classes (declaration of 'org.webrtc.EglBase' appears in /data/app/org.nativescript.application-rDCBmloXjAwRR_prpR1abQ==/base.apk)

StackTrace:
java.lang.NoSuchMethodError: No static method create()Lorg/webrtc/EglBase; in class Lorg/webrtc/EglBase; or its super classes (declaration of 'org.webrtc.EglBase' appears in /data/app/org.nativescript.application-rDCBmloXjAwRR_prpR1abQ==/base.apk)
	at co.fitcom.fancywebrtc.FancyWebRTCEglUtils.getRootEglBase(FancyWebRTCEglUtils.java:13)
	at co.fitcom.fancywebrtc.FancyWebRTC.lambda$init$0(FancyWebRTC.java:93)
	at co.fitcom.fancywebrtc.-$$Lambda$FancyWebRTC$jFoisGouehK4C4J-BYA5BfOZep4.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)

**Comment by rgill02** [comment]
You can take a look at this [thread](https://github.com/triniwiz/nativescript-webrtc/issues/31). I had the same issue and also found this related [thread](https://github.com/twilio/video-quickstart-android/issues/430) from another repo that I used to fix the problem. I downgraded my build gradle for android to version 3.4.2 like someone suggested and it worked for me. Obviously this isn't a real fix, just a temporary band aid, but if you can live with it for now then hopefully it helps.

**Comment by rgill02** [comment]
@AGregorc let me know if you are able to use WebRTCView correctly in your xml page. Since you and I seem to be actively using this library at the moment we should keep each other informed on any issues/fixes

**Comment by AGregorc** [comment]
@rgill02 well I haven't tried because I found something other to work on. I'll let you know when I find that repository interesting and start working on it again :)
