### ISSUE TITLE
PeerConnectionFactory.initialize was not called before creating a PeerConnectionFactory.

### ISSUE THREAD

**Issue by javatutorials2016** [triniwiz/nativescript-webrtc#56]
### Make sure to check the demo app(s) for sample usage 
Yes
### Make sure to check the existing issues in this repository 
Yes, checked
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

An uncaught Exception occurred on "pool-15-thread-1" thread.
PeerConnectionFactory.initialize was not called before creating a PeerConnectionFactory.

StackTrace:
java.lang.IllegalStateException: PeerConnectionFactory.initialize was not called before creating a PeerConnectionFactory.
	at org.webrtc.PeerConnectionFactory.checkInitializeHasBeenCalled(PeerConnectionFactory.java:325)
	at org.webrtc.PeerConnectionFactory.access$100(PeerConnectionFactory.java:26)
	at org.webrtc.PeerConnectionFactory$Builder.createPeerConnectionFactory(PeerConnectionFactory.java:269)
	at co.fitcom.fancywebrtc.FancyRTCPeerConnection.lambda$initFactory$0(FancyRTCPeerConnection.java:82)
	at co.fitcom.fancywebrtc.-$$Lambda$FancyRTCPeerConnection$4IDmnY0rxzeUFwWQUrmzEUXxX0Q.run(lambda)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

### Which platform(s) does your issue occur on?
- iOS/Android/Both  Android
- iOS/Android versions 
- emulator or device. What type of device? Device

### Please, provide the following version numbers that your issue occurs with:
"dependencies": {
    "@angular/animations": "^10.1.5",
    "@angular/common": "~10.0.9",
    "@angular/compiler": "~10.0.9",
    "@angular/core": "~10.0.9",
    "@angular/forms": "~10.0.9",
    "@angular/localize": "~10.0.9",
    "@angular/platform-browser": "~10.0.9",
    "@angular/platform-browser-dynamic": "~10.0.9",
    "@angular/router": "~10.0.9",
    "@angular/service-worker": "~10.0.9",
    "@nativescript/angular": "^10.1.7",
    "@nativescript/camera": "^5.0.2",
    "@nativescript/core": "~7.0.0",
    "@nativescript/theme": "~2.5.0",
    "@ng-bootstrap/ng-bootstrap": "^7.0.0",
    "@schoolsquirrel/letter-avatar": "^1.0.0",
    "@stomp/ng2-stompjs": "^7.2.0",
    "@types/node-rsa": "^1.0.0",
    "@types/socket.io-client": "^1.4.33",
    "aes-js": "^3.1.2",
    "angularx-social-login": "^3.2.1",
    "bootstrap": "^4.5.0",
    "constants": "0.0.2",
    "core-js": "^3.6.5",
    "cryptico": "^1.0.2",
    "crypto": "^1.0.1",
    "crypto-module": "^1.3.19",
    "event-source-polyfill": "^1.0.16",
    "idb": "^5.0.4",
    "mediasoup-client": "^3.6.12",
    "moment": "^2.27.0",
    "nativescript-oauth2": "^3.0.1",
    "nativescript-photoviewer": "^2.1.5",
    "nativescript-rsa": "^1.0.1-beta.2",
    "nativescript-secure-storage": "^2.6.2",
    "nativescript-socket.io": "^0.11.1",
    "nativescript-sse": "^4.0.2",
    "nativescript-ui-listview": "^9.0.2",
    "nativescript-videoplayer": "^5.0.1",
    "nativescript-webrtc-plugin": "^2.0.0-alpha.22",
}
- CLI: (run `tns --version` to fetch it)7.0.11
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project)

- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.
In IOS Emulator able to load to component and establish rtc connection with offer,answer candidate, only isssue that I face in IOS emulator is srcObject not displaying the remote/local video/audio. 
So I use Android device to test feature and I encounter the error.
### Is there any code involved? 
 - provide a code example to recreate the problem 

 - (EVEN BETTER) provide a .zip with application or refer to a repository with application where the problem is reproducible.

**Comment by javatutorials2016** [comment]
facing same error with the below example on android device. I added android.enableDexingArtifactTransform.desugaring=false in gradle.properties to resolve No static method create()Lorg/webrtc/EglBase; in class Lorg/webrtc/EglBase; or its super classes (declaration of 'org.webrtc.EglBase' appears in /data/app/org.nativescript.juzchat-1/base.apk) after that PeerConnectionFactory.initialize was not called before creating a PeerConnectionFactory start to happen.

https://github.com/triniwiz/nativescript-webrtc/tree/master/demo-ng/src/app/webrtc
